### ISSUE TITLE
Plugin not working for Elegoo Neptune 2s

### ISSUE THREAD

**Issue by iakymchuk** [TheJMaster28/ElegooNeptuneThumbnailPrusa#17]
Printer: ELEGOO Neptune 2s
Printer Firmware Version: V2.0.1
Prusa Version: 2.6.1
Plugin Version: 2.1.0
Operating System: Windows 11
Bug:
Last few months used a version from Molodos and it working fine with post-processing script parameters: C:\...\ElegooNeptuneThumbnails-Prusa.exe --printer=NEPTUNE2S;

Changed thumbnails size from 600x600 to 200x200 and script parameters to: 
"C:\...\thumbnail.exe" "--old_printer" "--img_size" "200x200" "--short_time_format";

The script successfully processed gcode but the image doesn't display on the printer screen.

**Comment by TheJMaster28** [comment]
Looks like old printers had a different format that I forgot to change. Fixed it in the latest release v2.1.1. Let me know if it doesn't work!
https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/releases/tag/v2.1.1
