### ISSUE TITLE
PrusaSlicer 2.6.1 Error

### ISSUE THREAD

**Issue by mattinflorence** [TheJMaster28/ElegooNeptuneThumbnailPrusa#3]
Tested with PrusaSlicer 2.6.1 and get an error...
![Capture](https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/assets/117344928/c7824868-1c00-48ca-a28e-8690442e45c0)

**Comment by TheJMaster28** [comment]
If you have the app.log that generates when it runs in the source folder of the thumbnail.exe, that might be helpful to see what the error is.  

I released a new version that I tested on 2.6.1 and was able to get it working, so you could also try that.
