### ISSUE TITLE
Prusa 2.6.1 and firmware 1.1.5.1a

### ISSUE THREAD

**Issue by knippo79** [TheJMaster28/ElegooNeptuneThumbnailPrusa#7]
I'm using Prusa 2.6.1 and Neptune 3 Pro with firmware 1.1.5.1a

I've set the post processing setting with the python script, thumb size to 200x200 and I did not get any error exporting the .gcode.
I got the thumbnail code in my .gcode but I did not see the preview on my printer display.

![Screenshot 2023-09-29 at 08 34 31](https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/assets/53086412/1bde931d-40c4-4aa4-a08a-c39629829a12)

Any idea?

**Comment by knippo79** [comment]
if you inspect the buddha .gcode made in Cura is completely different

![Screenshot 2023-09-29 at 08 49 43](https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/assets/53086412/7d91d865-5854-4d67-aaf2-e018dd349fe6)

**Comment by TheJMaster28** [comment]
If you have the app.log under where you unzipped it, I can see what is going on. It looks like it didn't create the new gcode at all from your screenshot. It should be something similar to the budda code with the `;gimage` and `;simage` at the top.

**Comment by knippo79** [comment]
You are right! sorry :)

Here my log error:

```
2023-09-29 08:43:55,169 - ERROR - Error occurred while running application.
Traceback (most recent call last):
  File "/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 229, in <module>
    obj.run()
  File "/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 189, in run
    new_thumbnail_gcode += self.parse_screenshot_new(prusa_thumbnail_decoded, 200, 200, ";gimage:")
  File "/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 117, in parse_screenshot_new
    p_dll = CDLL(dll_path)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/libColPic.dylib, 0x0006): tried: '/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/libColPic.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/libColPic.dylib' (no such file), '/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/libColPic.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

```

I think the problem is I'm running a MacBook with M1 processor.

**Comment by TheJMaster28** [comment]
Yeah, I think the dll that Elegoo uses for Mac is not compiled for the M1 macs. Someone else was able to get it to work within an x86_64 miniconda environment and running the script instead of the exe release. Maybe follow this: https://stackoverflow.com/questions/71691598/how-to-run-python-as-x86-with-rosetta2-on-arm-macos-machine

Then you can clone the repo, install the dependances, and put the path to the thumbnail.py script for the 'Post-processing scripts'

**Comment by knippo79** [comment]
Ok I was able to install a x86 version of python3 with (x86) homebrew.

I changed the path from "/usr/bin/python3" (ARM version) to "/usr/local/bin/python3" (x86 version) in post processing field but I get a new error in app.log

```
2023-10-03 08:42:17,565 - INFO - gcode input file from slicer: /var/folders/19/s3cs7gv108x7_4mwhzctxxn00000gn/T/.7575.gcode.pp
2023-10-03 08:42:17,604 - ERROR - End of file reached. Could not find thumbnail encoding in provided gcode file.
2023-10-03 08:42:17,604 - DEBUG - Decoding thumbnail from base64
2023-10-03 08:42:17,604 - ERROR - Error occurred while running application.
Traceback (most recent call last):
  File "/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 229, in <module>
    obj.run()
  File "/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 183, in run
    prusa_thumbnail_decoded = self.decode(prusa_thumbnail_str)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../Desktop/3dprint/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 67, in decode
    text_bytes = text.encode("ascii")
                 ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode' 
```

Any idea?

**Comment by TheJMaster28** [comment]
does your gcode file have the 200x200 thumbnail in it? Or is the slicer setting still at `200x200`? I am pushing a new release right now so you could also try that.

**Comment by knippo79** [comment]
Thanks man! you saved my day!

Here my code:

<img width="828" alt="Screenshot 2023-10-03 at 10 15 20" src="https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/assets/53086412/bb408ec9-c9ed-4c68-afae-05086c09b804">

I can't load it in the printer now but I'll let you know if everything is ok.

**Comment by knippo79** [comment]
it works!!!

![Uploading IMG_0912.jpeg…]()

**Comment by knippo79** [comment]
it works!!!

![IMG_0912](https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/assets/53086412/69ea428e-585b-4a33-9ca6-561955e5942e)

**Comment by TheJMaster28** [comment]
Glad you got it working!
